required by display-drivers/msm/sde/sde_kms.c
/mnt/sources/lineage/kernel/xiaomi/sm8635/../sm8635-modules/qcom/opensource/display-drivers/msm/sde/sde_kms.c:78:10: fatal error: 'soc/qcom/dcvs_boost.h' file not found
   78 | #include <soc/qcom/dcvs_boost.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~