linux/cpu_boost.h required by display-drivers/msm/sde/sde_kms.c
/tmp/src/android/kernel/xiaomi/sm8635/../sm8635-modules/qcom/opensource/display-drivers/msm/sde/sde_kms.c:77:10: fatal error: 'linux/cpu_boost.h' file not found
   77 | #include <linux/cpu_boost.h>

/tmp/src/android/kernel/xiaomi/sm8635/../sm8635-modules/qcom/opensource/display-drivers/msm/sde/sde_kms.h:69:57: note: expanded from macro 'SDE_ERROR'
   69 | #define SDE_ERROR(fmt, ...) pr_err("[sde error]" fmt, ##__VA_ARGS__)
...
make[2]: *** [/tmp/src/android/kernel/xiaomi/sm8635/Makefile:2138: ../sm8635-modules/qcom/opensource/display-drivers/msm] Error 2
make[2]: Leaving directory '/tmp/src/android/out/target/product/peridot/obj/KERNEL_OBJ'